Update 01~03.php
oz-urabe/weak-source pull request #16
Opened 2023-04-26 10:45 UTC by k-tachibana-oz

2023-04-26 11:17 UTC, k-tachibana-oz commented on 02.php
> +    }
htmlspecialcharsと同じことをjs でやろうとして
https://www.php.net/manual/ja/function.htmlspecialchars.php
を読んだりと、遠回りなことをやってました。

2023-04-26 11:19 UTC, k-tachibana-oz commented on 01.php
> +    value: <?php echo htmlspecialchars($_GET['show'], ENT_QUOTES, 'UTF-8'); ?>
最難関でした（個人差あり）

2023-05-09 11:29 UTC, ozv-s-urabe requested changes

2023-05-09 11:29 UTC, ozv-s-urabe commented on 02.php
> +    }
@k-tachibana-oz 
ナイスな不正解です。

この箇所は HTML のエスケープではなく javascript のエスケープをする必要がありますが、以下の 徳丸さんの `XSS対策:JavaScriptなどのエスケープ` 〜 その4 まで読むとわかるように、簡単ではありません。

https://github.com/oz-sysb/Improvement/wiki/%E3%82%BB%E3%82%AD%E3%83%A5%E3%82%A2%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3#javascript-%E3%81%AE%E7%94%9F%E6%88%90

ですので、HTML 要素に一旦書き出して、あとから JS で DOM の値を読み取るという手法を使うように推奨しています。

```
<input id="example" type="hidden" value="<?php echo htmlspecialchars($name, ENT_QUOTES, 'utf-8'); ?>" />

<script type="text/javascript"><![CDATA[
alert(document.getElementById("example").value);
//]]></script>
```

2023-05-09 11:29 UTC, ozv-s-urabe commented on 03.php
> +    $("#write").html(escapeHtml(decodeURIComponent(location.hash.substring(1))));
難しいことをしている感じですが、ここは HTMLエスケープ箇所ではないです。

`$("#write").text(decodeURIComponent(location.hash.substring(1)))` とする感じです。

2023-06-05 02:42 UTC, closed without merging